<?xml version="1.0" encoding="UTF-8"?>
<gml:FeatureCollection xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:fkbvn="https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gts="http://www.isotc211.org/2005/gts" gml:id="id88dcf5e7-1c4f-4a0c-a272-66e28419bc2e" xsi:schemaLocation="https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB/fkbvn https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB/fkbvn/fkbvn.xsd">
	<gml:boundedBy>
		<gml:Envelope srsName="EPSG:6173" srsDimension="3">
			<gml:lowerCorner>285590.78507 6745923.64602 125.57379</gml:lowerCorner>
			<gml:upperCorner>288884.21019 6748069.12989 135.87868</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169006_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169006</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169006_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288881.40132 6746520.5659 132.59932</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0426212921282307</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704518</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0315841580432687</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169006_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169006</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169006_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288884.21019 6746521.18009 132.44013</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0426212921282307</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704518</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0315841580432687</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169007_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169007</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169007_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288631.47172 6747050.32348 126.0</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.108441215974768</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704521</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0224991716668624</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169007_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169007</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169007_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288629.57092 6747049.48973 126.0</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.108441215974768</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704521</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0224991716668624</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169008_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169008</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169008_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288056.63064 6748068.26779 126.53595</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.239637949528153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704522</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0244670798855123</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169008_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169008</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169008_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288060.46418 6748069.12989 127.00551</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.239637949528153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704522</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0244670798855123</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169010_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169010</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169010_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288856.01829 6746577.44835 131.46051</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704519</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.981572181080945</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0496545862837152</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169010_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169010</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169010_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288858.52842 6746578.89035 131.62234</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704519</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.981572181080945</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0496545862837152</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169011_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169011</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169011_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288692.69789 6746944.88963 126.28565</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704520</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.978752142029134</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0947326197763738</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169011_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169011</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169011_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288690.86601 6746943.61834 126.12314</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704520</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.978752142029134</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0947326197763738</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169012_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169012</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169012_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288053.74581 6748065.75768 127.11402</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704523</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.976334584798426</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.239637949528153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114169012_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114169012</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169012_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288056.63064 6748068.26779 126.53595</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704523</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.976334584798426</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.239637949528153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114246714_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114246714</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114246714_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288395.64795 6747467.84447 125.96367</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.162256645186143</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704556</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0948817515888858</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114246714_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114246714</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114246714_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288391.10483 6747467.03361 125.57379</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.162256645186143</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704556</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0948817515888858</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.264606396_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>264606396</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.264606396_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287884.71929 6746539.12882 128.66164</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705463</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.261834297682911</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705752</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.264606396_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>264606396</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.264606396_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287889.5 6746551.3 128.5</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705463</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.261834297682911</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705752</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.290620590_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>290620590</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.290620590_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288434.31866 6747389.46789 125.72896</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704556</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.910475818364545</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.152633831788207</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.290620590_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>290620590</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.290620590_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>288438.15665 6747393.39154 126.16257</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704556</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.910475818364545</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>705183</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.152633831788207</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.376508729_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>376508729</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508729_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287294.27734 6746249.81987 135.87868</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650271</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.805652790816153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650430</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.543110890315252</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.376508729_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>376508729</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508729_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287307.58566 6746246.89452 135.7</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650271</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.805652790816153</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650430</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.543110890315252</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.376508730_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>376508730</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508730_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287311.0056 6746260.75346 135.24984</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650271</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.872712253311757</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650430</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.543110890315252</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.376508730_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>376508730</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508730_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287307.58566 6746246.89452 135.7</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650271</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.872712253311757</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650430</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.543110890315252</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.445661818_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>445661818</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.445661818_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286329.51001 6746106.88 126.2</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2389474</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2389481</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.823367578505077</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.445661818_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>445661818</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.445661818_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286333.32863 6746097.12445 126.38086</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2389474</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2389481</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.823367578505077</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.739012489_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>739012489</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.739012489_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>285590.78507 6746365.11532 125.64266</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1911209</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.404909171044934</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1911206</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.760211147955439</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.739012489_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>739012489</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.739012489_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>285593.66005 6746359.81656 125.84095</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1911209</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.404909171044934</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1911206</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.760211147955439</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.826297296_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>826297296</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.826297296_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287883.85039 6746541.4067 128.7</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704634</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0749278495309346</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650385</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0274550231169956</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.826297296_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>826297296</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.826297296_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>287889.5 6746551.3 128.5</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>704634</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0749278495309346</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>650385</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0274550231169956</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772828_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772828</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772828_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286613.84303 6745944.47892 126.74191</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100942</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.595497501605238</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100940</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.922557138675533</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772828_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772828</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772828_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286618.35374 6745940.4923 126.59953</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100942</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.595497501605238</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100940</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.922557138675533</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772829_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772829</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772829_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286742.66215 6745937.30656 127.3449</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100937</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.178426792393324</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2277929</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0732458043044832</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772829_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772829</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772829_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286752.53524 6745923.64602 127.09403</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100937</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.178426792393324</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2277929</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0732458043044832</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772830_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772830</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772830_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286766.19615 6745932.40213 127.62252</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100937</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0100050195719677</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2277929</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0726682216150344</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.905772830_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>905772830</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772830_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>286752.54693 6745923.73601 127.09734</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>3100937</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0100050195719677</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2277929</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0726682216150344</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
</gml:FeatureCollection>