<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection
    xmlns="http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/Elveg/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:wfs="http://www.opengis.net/wfs/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xsi:schemaLocation="http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/Elveg/2.0
    http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/Elveg/2.0/Elveg.xsd
    http://www.opengis.net/wfs/2.0
    http://schemas.opengis.net/wfs/2.0/wfs.xsd"
    timeStamp="2018-10-04T20:45:38Z"
    numberMatched="unknown"
    numberReturned="0">
	<wfs:member>
		<gml:Envelope srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
			<gml:lowerCorner>286329.51001 6745923.64602 125.57379</gml:lowerCorner>
			<gml:upperCorner>288884.21019 6747467.84447 135.87868</gml:upperCorner>
		</gml:Envelope>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169006_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169006</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169006_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288881.40132 6746520.5659 132.59932</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0426212921282307</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704518</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0315841580432687</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169006_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169006</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169006_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288884.21019 6746521.18009 132.44013</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0426212921282307</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704518</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0315841580432687</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169007_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169007</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169007_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288631.47172 6747050.32348 126.0</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.108441215974768</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704521</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0224991716668624</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169007_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169007</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169007_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288629.57092 6747049.48973 126.0</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.108441215974768</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704521</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0224991716668624</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169010_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169010</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169010_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288856.01829 6746577.44835 131.46051</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704519</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.981572181080945</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0496545862837152</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169010_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169010</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169010_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288858.52842 6746578.89035 131.62234</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704519</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.981572181080945</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0496545862837152</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169011_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169011</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169011_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288692.69789 6746944.88963 126.28565</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704520</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.978752142029134</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0947326197763738</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114169011_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114169011</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114169011_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288690.86601 6746943.61834 126.12314</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704520</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.978752142029134</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0947326197763738</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114246714_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114246714</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114246714_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288395.64795 6747467.84447 125.96367</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.162256645186143</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704556</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0948817515888858</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.114246714_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>114246714</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114246714_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288391.10483 6747467.03361 125.57379</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.162256645186143</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704556</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0948817515888858</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.264606396_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>264606396</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.264606396_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287884.71929 6746539.12882 128.66164</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705463</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.261834297682911</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705752</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>1.0</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.264606396_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>264606396</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.264606396_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287889.5 6746551.3 128.5</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705463</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.261834297682911</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705752</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>1.0</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.290620590_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>290620590</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.290620590_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288434.31866 6747389.46789 125.72896</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704556</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.910475818364545</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.152633831788207</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.290620590_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>290620590</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.290620590_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>288438.15665 6747393.39154 126.16257</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704556</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.910475818364545</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>705183</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.152633831788207</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.376508729_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>376508729</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508729_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287294.27734 6746249.81987 135.87868</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650271</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.805652790816153</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650430</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.543110890315252</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.376508729_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>376508729</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508729_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287307.58566 6746246.89452 135.7</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650271</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.805652790816153</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650430</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.543110890315252</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.376508730_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>376508730</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508730_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287311.0056 6746260.75346 135.24984</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650271</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.872712253311757</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650430</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.543110890315252</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.376508730_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>376508730</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.376508730_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287307.58566 6746246.89452 135.7</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650271</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.872712253311757</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650430</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.543110890315252</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.445661818_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>445661818</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.445661818_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286329.51001 6746106.88 126.2</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2389474</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>1.0</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2389481</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.823367578505077</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.445661818_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>445661818</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.445661818_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286333.32863 6746097.12445 126.38086</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2389474</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>1.0</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2389481</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.823367578505077</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.826297296_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>826297296</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.826297296_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287883.85039 6746541.4067 128.7</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704634</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0749278495309346</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650385</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0274550231169956</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.826297296_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>826297296</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.826297296_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>287889.5 6746551.3 128.5</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>704634</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0749278495309346</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>650385</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0274550231169956</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772828_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772828</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772828_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286613.84303 6745944.47892 126.74191</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100942</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.595497501605238</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100940</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.922557138675533</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772828_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772828</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772828_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286618.35374 6745940.4923 126.59953</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100942</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.595497501605238</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100940</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.922557138675533</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772829_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772829</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772829_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286742.66215 6745937.30656 127.3449</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100937</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.178426792393324</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2277929</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0732458043044832</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772829_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772829</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772829_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286752.53524 6745923.64602 127.09403</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100937</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.178426792393324</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2277929</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0732458043044832</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772830_0">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772830</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772830_0-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286766.19615 6745932.40213 127.62252</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100937</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0100050195719677</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2277929</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0726682216150344</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
	<wfs:member>
		<Svingerestriksjon gml:id="vegvesen.no.nvdb.905772830_1">
			<identifikasjon>
				<Identifikasjon>
					<lokalId>905772830</lokalId>
					<navnerom>vegvesen.no.nvdb</navnerom>
					<versjonId>1</versjonId>
				</Identifikasjon>
			</identifikasjon>
			<posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.905772830_1-0" srsName="http://www\.opengis\.net/def/crs/epsg/0/6173" srsDimension="3">
					<gml:pos>286752.54693 6745923.73601 127.09734</gml:pos>
				</gml:Point>
			</posisjon>
			<svingeforbudFra>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>3100937</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0100050195719677</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudFra>
			<svingeforbudTil>
				<LineærPosisjonPunkt>
					<lineærReferanseMetode>normalisert</lineærReferanseMetode>
					<lenkesekvens>
						<Identifikasjon>
							<lokalId>2277929</lokalId>
							<navnerom>vegvesen.no.nvdb.rls</navnerom>
						</Identifikasjon>
					</lenkesekvens>
					<posisjon>0.0726682216150344</posisjon>
				</LineærPosisjonPunkt>
			</svingeforbudTil>
		</Svingerestriksjon>
	</wfs:member>
</wfs:FeatureCollection>