<?xml version="1.0" encoding="UTF-8"?>
<gml:FeatureCollection xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:fkbvn="https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gts="http://www.isotc211.org/2005/gts" gml:id="ide83ed7b7-daa0-4579-a73b-88a411bf44bd" xsi:schemaLocation="https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB/fkbvn https://raw.githubusercontent.com/jetgeo/NVDBGML/master/XSD/NVDB/fkbvn/fkbvn.xsd">
	<gml:boundedBy>
		<gml:Envelope srsName="EPSG:6173" srsDimension="3">
			<gml:lowerCorner>243345.48093 6814987.15512 184.05593</gml:lowerCorner>
			<gml:upperCorner>246836.40289 6823813.6 187.3</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173026_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173026</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173026_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243745.98938 6822394.54465 185.39999</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0992187933109688</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060030</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0355255911466552</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173026_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173026</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173026_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243748.36668 6822395.69484 185.29744</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0992187933109688</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060030</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0355255911466552</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173027_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173027</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173027_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243377.97204 6822836.48207 185.89936</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.157183613713804</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060031</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0317138329672559</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173027_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173027</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173027_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243376.50953 6822835.77531 186.0</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.157183613713804</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060031</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0317138329672559</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173028_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173028</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173028_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243530.5 6823800.19995 187.3</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060772</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.345376271805544</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1061022</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173028_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173028</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173028_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243526.3 6823813.6 187.3</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060772</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.345376271805544</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1061022</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>1.0</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173029_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173029</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173029_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243798.65342 6822294.41986 185.10001</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060032</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.973769372987949</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0878416478035718</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173029_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173029</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173029_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243799.58159 6822294.96947 185.25248</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060032</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.973769372987949</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0878416478035718</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173030_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173030</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173030_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243346.85336 6822899.87714 184.90896</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060033</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.974128120365041</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.164286941539279</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.114173030_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>114173030</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.114173030_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>243345.48093 6822899.1514 185.8</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060033</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.974128120365041</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1060619</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.164286941539279</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.393979012_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>393979012</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.393979012_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>246784.89265 6815012.27362 184.09332</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.176102020101722</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360515</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.93220745051056</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.393979012_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>393979012</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.393979012_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>246782.33488 6815008.98696 184.05593</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.176102020101722</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360515</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.93220745051056</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.393979013_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>393979013</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.393979013_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>246834.5474 6814987.15512 184.62033</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.170150398251922</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360516</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0744919447919955</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.393979013_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>393979013</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.393979013_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>246836.40289 6814989.56604 184.54884</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.170150398251922</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360516</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0744919447919955</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.394093128_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>394093128</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.394093128_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>245594.94815 6816232.40098 185.79219</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.377124675725049</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360558</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0815057692275701</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.394093128_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>394093128</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.394093128_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>245597.17989 6816233.29616 185.79185</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.377124675725049</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>2360558</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.0815057692275701</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.591080091_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>591080091</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.591080091_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>244201.47667 6821542.31152 185.7</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.999808318498445</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1003491</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.00369556218459292</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.591080091_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>591080091</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.591080091_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>244206.84706 6821537.29431 185.66824</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.999808318498445</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1003491</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.00369556218459292</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.591080092_0">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>591080092</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.591080092_0-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>244207.31324 6821537.17669 185.65717</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1003491</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.00400591537640203</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.999033526542645</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
	<gml:featureMember>
		<fkbvn:Svingerestriksjon gml:id="vegvesen.no.nvdb.591080092_1">
			<fkbvn:identifikasjon>
				<fkbvn:Identifikasjon>
					<fkbvn:lokalId>591080092</fkbvn:lokalId>
					<fkbvn:navnerom>vegvesen.no.nvdb</fkbvn:navnerom>
					<fkbvn:versjonId>1</fkbvn:versjonId>
				</fkbvn:Identifikasjon>
			</fkbvn:identifikasjon>
			<fkbvn:posisjon>
				<gml:Point gml:id="vegvesen.no.nvdb.591080092_1-0" srsName="EPSG:6173" srsDimension="3">
					<gml:pos>244201.18051 6821535.07486 185.7</gml:pos>
				</gml:Point>
			</fkbvn:posisjon>
			<fkbvn:svingeforbudFra>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1003491</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.00400591537640203</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudFra>
			<fkbvn:svingeforbudTil>
				<fkbvn:LineærPosisjonPunkt>
					<fkbvn:lineærReferanseMetode>normalisert</fkbvn:lineærReferanseMetode>
					<fkbvn:lenkesekvens>
						<fkbvn:Identifikasjon>
							<fkbvn:lokalId>1059995</fkbvn:lokalId>
							<fkbvn:navnerom>vegvesen.no.nvdb.rls</fkbvn:navnerom>
						</fkbvn:Identifikasjon>
					</fkbvn:lenkesekvens>
					<fkbvn:posisjon>0.999033526542645</fkbvn:posisjon>
				</fkbvn:LineærPosisjonPunkt>
			</fkbvn:svingeforbudTil>
		</fkbvn:Svingerestriksjon>
	</gml:featureMember>
</gml:FeatureCollection>